#!/bin/bash -e

rm -f /sbin/containerpilot-runonce /container/tool/containerpilot-runonce

mkdir -p $AP_STATE_DIR

containerpilot-render
# Chain into the new preStart
eval $(jq '.preStart' /etc/containerpilot.json | sed 's/"//g')
rv=$?

# Reload config
kill -s HUP 1

exit $rv
