#!/usr/bin/python -u
import os, os.path, shutil, subprocess
from glob import glob


SERVICE_DIR = os.environ["AP_SERVICE_DIR"]
GLOBAL_CONSUL_DIR = "/etc/consul.d"
GLOBAL_CONTAINERPILOT_DIR = "/etc/containerpilot.d"
INSTALL_FILENAME = "install.sh"
PROCESS_FILENAME = "process.sh"
nb_process = 0

def mkdir(dir_name):
    try:
        os.mkdir(dir_name)
    except OSError:
        pass

mkdir(GLOBAL_CONSUL_DIR)
mkdir(GLOBAL_CONTAINERPILOT_DIR)

print("install-service")
# Auto run global install script if available
global_install_file=os.path.join(SERVICE_DIR, INSTALL_FILENAME)
if os.path.isfile(global_install_file):
    print("run " + global_install_file)
    subprocess.call([global_install_file],shell=True)

    print("remove " + global_install_file+ "\n")
    os.remove(global_install_file)

# For each service in /container/service
#   - execute install script
#   - copy consul.d and containerpilot.d config files
for service in sorted(os.listdir(SERVICE_DIR)):

    install_file=os.path.join(SERVICE_DIR, service, INSTALL_FILENAME)
    if os.path.isfile(install_file):
        print("run " + install_file)
        subprocess.call([install_file],shell=True)

        print("remove " + install_file)
        os.remove(install_file)

    src_dst_dirs = [ (os.path.join(SERVICE_DIR, service, os.path.basename(dst_dir)), dst_dir)
                        for dst_dir in [ GLOBAL_CONSUL_DIR, GLOBAL_CONTAINERPILOT_DIR ] ]
    for (src, dst) in src_dst_dirs:
        for src_file in glob(os.path.join(src, '*')):
            shutil.copy2(src_file, dst)

    process_file=os.path.join(SERVICE_DIR, service, PROCESS_FILENAME)
    if os.path.isfile(process_file):
        nb_process += 1

